{"name": "Проверка наличия ошибки если неправильно указать логин или пароль/авторизация под несуществующим пользователем ", "status": "passed", "steps": [{"name": "вход курьера в систему", "status": "passed", "parameters": [{"name": "login_data", "value": "{'login': 'wrong55login', 'password': 'wron55password'}"}], "start": 1741989226058, "stop": 1741989226372}], "start": 1741989226057, "stop": 1741989226373, "uuid": "3dada912-6437-4ed9-840f-bb84063de011", "historyId": "e79e6ce828437ecf31a6932a2c0187b9", "testCaseId": "e79e6ce828437ecf31a6932a2c0187b9", "fullName": "tests.test_courier_login.TestLoginCourier#test_login_with_incorrect_credentials_raises_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "elishakh"}, {"name": "thread", "value": "31752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}